api:
  image:
    repository: ghcr.io/nullneo/shopup-api
    tag: "dev"
    digest: "sha256:3da90f1424f74278b755909a5b8065cac08309c9db3ac0279a8a94819c249ffe"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: api.shopup.localhost
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-tls
        hosts: [ api.shopup.localhost ]

postgresql:
  enabled: true
  auth:
    username: shopup
    password:
    database: shopup
  primary:
    persistence:
      size: 5Gi
