apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.api.DATABASE_URL is required" .Values.secrets.api.DATABASE_URL | quote }}