name: api-ci
on:
  push:
    paths:
      - 'services/**'
      - '.github/workflows/api.yml'
      - 'deploy/**'
      - 'scripts/**'
  pull_request:
    paths:
      - 'services/api/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./services/api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/nullneo/shopup-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy scan (HIGH/CRITICAL fail)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/nullneo/shopup-api:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'